/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Vlasnik;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author X
 */
public class DodajVlasnika extends javax.swing.JFrame {

    /**
     * Creates new form DodajVlasnika
     */
    public DodajVlasnika() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Salon za sisanje pasa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImeVlasnika = new javax.swing.JLabel();
        lblPrezimeVlasnika = new javax.swing.JLabel();
        lblBrojTelefonaVlasnika = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBrojTelefona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSacuvajVlasnika = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos vlasnika", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblImeVlasnika.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblImeVlasnika.setText("Ime:");

        lblPrezimeVlasnika.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrezimeVlasnika.setText("Prezime:");

        lblBrojTelefonaVlasnika.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBrojTelefonaVlasnika.setText("Broj telefona:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("+381");

        btnSacuvajVlasnika.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSacuvajVlasnika.setForeground(new java.awt.Color(204, 0, 0));
        btnSacuvajVlasnika.setText("Sacuvaj vlasnika");
        btnSacuvajVlasnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajVlasnikaActionPerformed(evt);
            }
        });

        btnOtkazi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOtkazi.setForeground(new java.awt.Color(204, 0, 0));
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImeVlasnika)
                            .addComponent(lblPrezimeVlasnika)
                            .addComponent(lblBrojTelefonaVlasnika))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtIme, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrojTelefona))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSacuvajVlasnika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImeVlasnika)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezimeVlasnika)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojTelefonaVlasnika)
                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnSacuvajVlasnika))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajVlasnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajVlasnikaActionPerformed
        try {
            validacija();
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            String brojTelefona = txtBrojTelefona.getText();
            
            Vlasnik v = new Vlasnik();
            v.setIme(ime);
            v.setPrezime(prezime);
            v.setBrojTelefona(brojTelefona);
            
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.DODAJ_VLASNIKA);
            kz.setParametar(v);
            
            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            Vlasnik vlasnik = (Vlasnik) so.getOdgovor();
            if(vlasnik != null){
                JOptionPane.showMessageDialog(this, "Vlasnik je uspesno ubacen u sistem.");
                srediFormu();
            }else{
                JOptionPane.showMessageDialog(this, "Vlasnik nije ubacen! Pokusajte ponovo.");
                srediFormu();
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajVlasnikaActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajVlasnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajVlasnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajVlasnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajVlasnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DodajVlasnika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvajVlasnika;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBrojTelefonaVlasnika;
    private javax.swing.JLabel lblImeVlasnika;
    private javax.swing.JLabel lblPrezimeVlasnika;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void validacija() throws Exception {
        String greska = "";
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String brojTelefona = txtBrojTelefona.getText();
        boolean samoSlovaIme = samoSlova(ime);
        boolean samoSlovaPrezime = samoSlova(prezime);
        boolean samoCifreIPlus = samoCifreIPlus(brojTelefona);

        if (txtIme.getText().isEmpty()) {
            greska += "Morate uneti ime!\n";
        }
        if (!samoSlovaIme) {
            greska += "Ime mora da sadrzi samo slova!\n";
        }
        if (txtPrezime.getText().isEmpty()) {
            greska += "Morate uneti prezime!\n";
        }
        if (!samoSlovaPrezime) {
            greska += "Prezime mora sadrzati samo slova!\n";
        }
        if (txtBrojTelefona.getText().isEmpty()) {
            greska += "Morate uneti broj telefona!\n";
        }
        if (!brojTelefona.startsWith("+3816")) {
            greska += "Broj telefona mora poceti sa '+3816'!\n";
        }
        if(brojTelefona.length() != 13){
            greska += "Broj telefona mora da sadrzi 13 cifara! Pokusajte ponovo. \n";
        }
        if (!greska.isEmpty()) {
            throw new Exception(greska);
        }
    }

    private boolean samoSlova(String string) {
        for (Character slovo : string.toCharArray()) {
            if (!Character.isLetter(slovo)) {
                return false;
            }
        }
        return true;
    }

    private boolean samoCifreIPlus(String string) {
        for (Character slovo : string.toCharArray()) {
            if (slovo == '+') {
                continue;
            }
            if (!Character.isDigit(slovo)) {
                return false;
            }
        }
        return true;
    }

    private void srediFormu() {
        txtIme.setText("");
        txtPrezime.setText("");
        txtBrojTelefona.setText("");
    }
}
