/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Ljubimac;
import domen.OpstiDomenskiObjekat;
import domen.Rezervacija;
import domen.StavkaRezervacije;
import domen.Usluga;
import domen.Zaposleni;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.ModelTabeleStavkaRezervacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author X
 */
public class DodajRezervaciju extends javax.swing.JFrame {

    int ukupnoVremeTrajanja = 0;
    double ukupnaCena = 0;
    Zaposleni ulogovani;
    Rezervacija rezervacija;
    String status;
    

    DodajRezervaciju(Rezervacija r) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Salon za sisanje pasa");
        popuniComboUsluga();
        popuniComboLjubimaca();
        tblStavkaRezervacije.setModel(new ModelTabeleStavkaRezervacije());
        rezervacija = r;
        this.status = "izmena";
    }

    public Zaposleni getUlogovani() {
        return ulogovani;
    }

    public void setUlogovani(Zaposleni ulogovani) {
        this.ulogovani = ulogovani;
    }

    public JLabel getLblUlogovaniZaposleni() {
        return lblUlogovaniZaposleni;
    }

    public void setLblUlogovaniZaposleni(JLabel lblUlogovaniZaposleni) {
        this.lblUlogovaniZaposleni = lblUlogovaniZaposleni;
    }

    /**
     * Creates new form DodajRezervaciju
     */
    public DodajRezervaciju() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Salon za sisanje pasa");
        popuniComboUsluga();
        popuniComboLjubimaca();
        tblStavkaRezervacije.setModel(new ModelTabeleStavkaRezervacije());
        this.status = "unos";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkaRezervacije = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbUsluga = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOpisStavkeRezervacije = new javax.swing.JTextArea();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        btnSacuvajRezervaciju = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblUlogovaniZaposleni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDatumRezervacije = new javax.swing.JFormattedTextField();
        txtOpisRezervacije = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblPVTrajanja = new javax.swing.JLabel();
        lblUkupnaCena = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbLjubimci = new javax.swing.JComboBox();
        btnPrikazi = new javax.swing.JButton();
        btnIzracunaj = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rezervacija", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stavka rezervacije", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblStavkaRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkaRezervacije);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Usluga:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Opis:");

        cmbUsluga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtOpisStavkeRezervacije.setColumns(20);
        txtOpisStavkeRezervacije.setRows(5);
        jScrollPane2.setViewportView(txtOpisStavkeRezervacije);

        btnDodajStavku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDodajStavku.setText("Dodaj stavku ");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        btnSacuvajRezervaciju.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacuvajRezervaciju.setForeground(new java.awt.Color(204, 0, 0));
        btnSacuvajRezervaciju.setText("Sacuvaj rezervaciju");
        btnSacuvajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajRezervacijuActionPerformed(evt);
            }
        });

        btnOtkazi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        jLabel9.setText("Ulogovani zaposleni:");

        lblUlogovaniZaposleni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnOtkazi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnObrisiStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSacuvajRezervaciju, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUlogovaniZaposleni)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajStavku))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnObrisiStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSacuvajRezervaciju)
                        .addGap(12, 12, 12)
                        .addComponent(btnOtkazi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblUlogovaniZaposleni)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Datum:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Opis:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Projektovano vreme trajanja:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ukupna cena:");

        txtDatumRezervacije.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm"))));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("dd.MM.yyyy");

        lblPVTrajanja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPVTrajanja.setText("vreme trajanja");

        lblUkupnaCena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUkupnaCena.setText("ukupna cena");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ljubimac:");

        cmbLjubimci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPrikazi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrikazi.setText("Prikazi");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnIzracunaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIzracunaj.setText("Izracunaj");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatumRezervacije)
                            .addComponent(txtOpisRezervacije)
                            .addComponent(cmbLjubimci, 0, 344, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPVTrajanja)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(123, 123, 123)
                        .addComponent(lblUkupnaCena)
                        .addGap(131, 131, 131)
                        .addComponent(btnIzracunaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDatumRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOpisRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbLjubimci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPVTrajanja)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUkupnaCena)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnIzracunaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        JOptionPane.showMessageDialog(this, cmbLjubimci.getSelectedItem());
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        ModelTabeleStavkaRezervacije mt = (ModelTabeleStavkaRezervacije) tblStavkaRezervacije.getModel();
        int brojStavki = mt.getLista().size();
        Usluga u = (Usluga) cmbUsluga.getSelectedItem();
        String opis = txtOpisStavkeRezervacije.getText();
        StavkaRezervacije sr = new StavkaRezervacije();
        sr.setRbStavke(brojStavki + 1);
        sr.setOpis(opis);
        sr.setUsluga(u);
        mt.dodajUTabelu(sr);
        ukupnaCena += sr.getUsluga().getCenaUsluge();
        ukupnoVremeTrajanja += sr.getUsluga().getVremeTrajanja();
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        int red = tblStavkaRezervacije.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku koju zelite obrisati.");
        } else {
            ModelTabeleStavkaRezervacije mt = (ModelTabeleStavkaRezervacije) tblStavkaRezervacije.getModel();
            StavkaRezervacije sr = (StavkaRezervacije) mt.getLista().get(red);
            ukupnaCena = ukupnaCena - sr.getUsluga().getCenaUsluge();
            ukupnoVremeTrajanja = ukupnoVremeTrajanja - sr.getUsluga().getVremeTrajanja();
            mt.obrisiStavku(red);
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed
        lblPVTrajanja.setText(String.valueOf(ukupnoVremeTrajanja) + " min");
        Ljubimac lj = (Ljubimac) cmbLjubimci.getSelectedItem();
        if(lj.getVlasnik().getIme().equals("nema")){
            ukupnaCena = 0;
            lblUkupnaCena.setText(ukupnaCena + " dinara");
        }else{
            lblUkupnaCena.setText(String.valueOf(ukupnaCena) + " dinara");
        }
        
    }//GEN-LAST:event_btnIzracunajActionPerformed

    private void btnSacuvajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajRezervacijuActionPerformed
        try {
            ModelTabeleStavkaRezervacije mt = (ModelTabeleStavkaRezervacije) tblStavkaRezervacije.getModel();
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            Date datum = sdf.parse(txtDatumRezervacije.getText());
            
            if (datum.compareTo(new Date()) < 0) {
                JOptionPane.showMessageDialog(this, "Datum rezervacije ne moze biti pre danasnjeg datume! Unesite ponovo datum.");
            }
            String opis = txtOpisRezervacije.getText();
            Ljubimac lj = (Ljubimac) cmbLjubimci.getSelectedItem();
            Rezervacija r = new Rezervacija();
            r.setDatum(datum);
            r.setOpis(opis);
            r.setLjubimac(lj);
            if(lj.getVlasnik().getIme().equals("nema")){
                r.setUkupnaCena(0);
            }else{
                r.setUkupnaCena(ukupnaCena);
            }
            r.setUkupnoVremeTrajanja(ukupnoVremeTrajanja);
            r.setZaposleni(ulogovani);
            List<OpstiDomenskiObjekat> stavke = mt.getLista();
            for (OpstiDomenskiObjekat odo : stavke) {
                StavkaRezervacije s = (StavkaRezervacije) odo;
                s.setRezervacija(r);
            }
            stavke.toString();
            r.setListaStavki(stavke);

            if (status.equals("izmena")) {
                rezervacija.setDatum(datum);
                rezervacija.setOpis(opis);
                rezervacija.setLjubimac(lj);
                rezervacija.setUkupnaCena(ukupnaCena);
                rezervacija.setUkupnoVremeTrajanja(ukupnoVremeTrajanja);
                rezervacija.setZaposleni(ulogovani);
                List<OpstiDomenskiObjekat> stavkeR = mt.getLista();
                for (OpstiDomenskiObjekat odo : stavke) {
                    StavkaRezervacije s = (StavkaRezervacije) odo;
                    s.setRezervacija(rezervacija);
                }
                stavke.toString();
                rezervacija.setListaStavki(stavke);
                KlijentskiZahtev kz = new KlijentskiZahtev();
                kz.setOperacija(Operacije.IZMENI_REZERVACIJU);
                kz.setParametar(rezervacija);
                Komunikacija.getInstance().posaljiZahtev(kz);
                ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
                Rezervacija rez = (Rezervacija) so.getOdgovor();
                if (rez != null) {
                    JOptionPane.showMessageDialog(this, "Rezervacija je uspesno izmenjena u sistemu");
                } else {
                    JOptionPane.showMessageDialog(this, "Greska kod izmene rezervacije u sistemu! Pokusajte ponovo");
                }
            }

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.DODAJ_REZERVACIJU);
            kz.setParametar(r);
            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            Rezervacija rez = (Rezervacija) so.getOdgovor();
            if (rez != null) {
                JOptionPane.showMessageDialog(this, "Rezervacija je uspesno uneta u sistem");
            } else {
                JOptionPane.showMessageDialog(this, "Greska kod unosa rezervacije u sistem! Pokusajte ponovo");
            }

        } catch (ParseException ex) {
            Logger.getLogger(DodajRezervaciju.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Greska kod datuma.");
        }
    }//GEN-LAST:event_btnSacuvajRezervacijuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajRezervaciju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajRezervaciju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajRezervaciju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajRezervaciju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DodajRezervaciju().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton btnSacuvajRezervaciju;
    private javax.swing.JComboBox cmbLjubimci;
    private javax.swing.JComboBox cmbUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPVTrajanja;
    private javax.swing.JLabel lblUkupnaCena;
    private javax.swing.JLabel lblUlogovaniZaposleni;
    private javax.swing.JTable tblStavkaRezervacije;
    private javax.swing.JFormattedTextField txtDatumRezervacije;
    private javax.swing.JTextField txtOpisRezervacije;
    private javax.swing.JTextArea txtOpisStavkeRezervacije;
    // End of variables declaration//GEN-END:variables

    private void popuniComboUsluga() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_USLUGE);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<OpstiDomenskiObjekat> listaUsluga = (List<OpstiDomenskiObjekat>) so.getOdgovor();
        cmbUsluga.removeAllItems();
        for (OpstiDomenskiObjekat usluga : listaUsluga) {
            cmbUsluga.addItem(usluga);
        }
    }

    private void popuniComboLjubimaca() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_LJUBIMCE);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<OpstiDomenskiObjekat> listaLjubimaca = (List<OpstiDomenskiObjekat>) so.getOdgovor();
        cmbLjubimci.removeAllItems();
        for (OpstiDomenskiObjekat ljubimac : listaLjubimaca) {
            cmbLjubimci.addItem(ljubimac);
        }
    }

}
