/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Ljubimac;
import domen.OpstiDomenskiObjekat;
import domen.Vlasnik;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacije;
import modeli.ModelTabeleLjubimci;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author X
 */
public class PretragaLjubimaca extends javax.swing.JFrame {

    /**
     * Creates new form PretragaLjubimaca
     */
    public PretragaLjubimaca() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Salon za sisanje pasa");
        tblLjubimci.setModel(new ModelTabeleLjubimci());
        popuniComboVlasnika();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbVlasnik = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLjubimci = new javax.swing.JTable();
        btnIzmeniLjubimca = new javax.swing.JButton();
        btnObrisiLjubimca = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        btnPretraziLjubimce = new javax.swing.JButton();
        btnRefresujVlasnike = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga ljubimaca", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Izaberite vlasnika:");

        cmbVlasnik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblLjubimci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLjubimci);

        btnIzmeniLjubimca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnIzmeniLjubimca.setForeground(new java.awt.Color(204, 0, 0));
        btnIzmeniLjubimca.setText("Izmeni ljubimca");
        btnIzmeniLjubimca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniLjubimcaActionPerformed(evt);
            }
        });

        btnObrisiLjubimca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnObrisiLjubimca.setForeground(new java.awt.Color(204, 0, 0));
        btnObrisiLjubimca.setText("Obrisi ljubimca");
        btnObrisiLjubimca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiLjubimcaActionPerformed(evt);
            }
        });

        btnOtkazi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnOtkazi.setForeground(new java.awt.Color(204, 0, 0));
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnPretraziLjubimce.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPretraziLjubimce.setForeground(new java.awt.Color(204, 0, 0));
        btnPretraziLjubimce.setText("Pretrazi");
        btnPretraziLjubimce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziLjubimceActionPerformed(evt);
            }
        });

        btnRefresujVlasnike.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRefresujVlasnike.setForeground(new java.awt.Color(204, 0, 0));
        btnRefresujVlasnike.setText("Refresuj");
        btnRefresujVlasnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresujVlasnikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(btnRefresujVlasnike, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPretraziLjubimce, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnIzmeniLjubimca)
                                .addGap(76, 76, 76)
                                .addComponent(btnObrisiLjubimca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziLjubimce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresujVlasnike)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniLjubimca)
                    .addComponent(btnObrisiLjubimca)
                    .addComponent(btnOtkazi))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnPretraziLjubimceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziLjubimceActionPerformed
        Vlasnik vl = (Vlasnik) cmbVlasnik.getSelectedItem();
        Ljubimac lj = new Ljubimac();
        lj.setVlasnik(vl);
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.NADJI_LJUBIMCE);
        kz.setParametar(lj);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<OpstiDomenskiObjekat> listaLjubimaca = (List<OpstiDomenskiObjekat>) so.getOdgovor();
        ModelTabeleLjubimci mt = (ModelTabeleLjubimci) tblLjubimci.getModel();
        mt.popuniTabelu(listaLjubimaca);
        
    }//GEN-LAST:event_btnPretraziLjubimceActionPerformed

    private void btnRefresujVlasnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresujVlasnikeActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_btnRefresujVlasnikeActionPerformed

    private void btnIzmeniLjubimcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniLjubimcaActionPerformed
        int red = tblLjubimci.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Izaberite ljubimca koga zelite da izmenite!");
        }else{
            ModelTabeleLjubimci mt = (ModelTabeleLjubimci) tblLjubimci.getModel();
            Ljubimac lj = (Ljubimac) mt.getLista().get(red);
            IzmenaLjubimca iz = new IzmenaLjubimca(this, true, lj);
            iz.setVisible(true);
            //this.setVisible(false);
        }
    }//GEN-LAST:event_btnIzmeniLjubimcaActionPerformed

    private void btnObrisiLjubimcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiLjubimcaActionPerformed
        int red = tblLjubimci.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Izaberite ljubimca koga zelite da obrisete!");
        }else{
            ModelTabeleLjubimci mt = (ModelTabeleLjubimci) tblLjubimci.getModel();
            Ljubimac lj = (Ljubimac) mt.getLista().get(red);
            int potvrda = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite obrisati izabranog ljubimca?");
            if(potvrda == 0){
                KlijentskiZahtev kz = new KlijentskiZahtev();
                kz.setOperacija(Operacije.OBRISI_LJUBIMCA);
                kz.setParametar(lj);
                Komunikacija.getInstance().posaljiZahtev(kz);
                ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
                Ljubimac obrisaniLjubimac = (Ljubimac) so.getOdgovor();
                if(obrisaniLjubimac != null){
                    JOptionPane.showMessageDialog(this, "Ljubimac je uspesno izbrisan iz sistema.");
                }else{
                    JOptionPane.showMessageDialog(this, "Greska prilikom brisanja ljubimca. Pokusajte ponovo.");
                }
            }
        }
    }//GEN-LAST:event_btnObrisiLjubimcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaLjubimaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaLjubimaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaLjubimaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaLjubimaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaLjubimaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniLjubimca;
    private javax.swing.JButton btnObrisiLjubimca;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPretraziLjubimce;
    private javax.swing.JButton btnRefresujVlasnike;
    private javax.swing.JComboBox cmbVlasnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLjubimci;
    // End of variables declaration//GEN-END:variables

    

    private void popuniTabelu() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_LJUBIMCE);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<OpstiDomenskiObjekat> listaLjubimaca = (List<OpstiDomenskiObjekat>) so.getOdgovor();
        ModelTabeleLjubimci mt = (ModelTabeleLjubimci) tblLjubimci.getModel();
        mt.dodajLjubimceUListu(listaLjubimaca);
    }

    private void popuniComboVlasnika() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_VLASNIKE);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<OpstiDomenskiObjekat> listaVlasnika = (List<OpstiDomenskiObjekat>) so.getOdgovor();
        cmbVlasnik.removeAllItems();
        for (OpstiDomenskiObjekat vlasnik : listaVlasnika) {
            cmbVlasnik.addItem(vlasnik);
        }
    }
}
